### ISSUE TITLE
copy paste problem

### ISSUE THREAD

**Issue by goranopacic** [aws-samples/serverless-snippets#18]
if you click on that copy icon in the corner, copy/paste doesn't work. if you click anywhere else it works

<img width="755" alt="Screenshot 2022-10-13 at 12 48 23" src="https://user-images.githubusercontent.com/34538947/195578238-c26c7a19-424d-4019-81c8-22ed6dbdb9a1.png">

**Comment by boyney123** [comment]
Thanks, now fixed
