### ISSUE TITLE
us-west-1 reagion set by default

### ISSUE THREAD

**Issue by goranopacic** [aws-samples/serverless-snippets#19]
region is set to region=us-east-1 by default iwhen you click "Open in Cloudwatch insights" button.

if you remove it form the link it goes to my default or already selected region.
Can you remove the region?

Here is an example link:

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272022-10-13T10*3A44*3A34.353Z$257Estart$257E$25272022-10-05T22*3A00*3A00.000Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527UTC$257EeditorString$257E$2527*23*20Number*20of*20exceptions*20per*20hour*0Afilter*20@message*20like*20/Exception/*20*0A*20*20*20*20*7C*20stats*20count*28**29*20as*20exceptionCount*20by*20bin*281h*29*0A*20*20*20*20*7C*20sort*20exceptionCount*20desc$257EisLiveTail$257Efalse$257EqueryId$257E$2527494fd614-b108-4295-b59a-770d605d9ee2$2529$2529

**Comment by boyney123** [comment]
Thanks @goranopacic I will take a look at this!

**Comment by boyney123** [comment]
Now fixed, thanks for raising the issue
