### ISSUE TITLE
New snippet submission - Lambda cold starts count and init duration

### ISSUE THREAD

**Issue by m-radzikowski** [aws-samples/serverless-snippets#2]
To submit a template to the Serverless Snippets Collection, submit an issue with the following information.

**To learn more about submitting a pattern, read the [publishing guidelines page](https://github.com/aws-samples/serverless-snippets/blob/main/PUBLISHING.md). and [added a new snippet guide](https://github.com/aws-samples/serverless-snippets/blob/main/ADDING_SNIPPET.md).**

1. Use the model template located at https://github.com/aws-samples/serverless-snippets/tree/main/_snippet-model to set up a README, snipet-data.json (metadata) and your snippet code (snippet.txt).

If you want multiple code examples in your snippet or support tabbed code examples (multi runtimes for example) then follow the guide for [added a new snippet](https://github.com/aws-samples/serverless-snippets/blob/main/ADDING_SNIPPET.md).

## GitHub PR for template: #1 

There are already two snippets to count the Lambda cold starts. However, this snippet extracts the initialization duration during the cold start and provides the min, max, and avg initialization time.

**Comment by boyney123** [comment]
Thanks for the pull request @m-radzikowski 

First one too! 😍

**Comment by boyney123** [comment]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/3268013/184820008-07b3b5e6-bc05-4641-b8c6-a9eda4bb9908.png">
