### ISSUE TITLE
Missing runtime for snippet Amazon S3 trigger to invoke a Lambda function

### ISSUE THREAD

**Issue by jhernandis** [aws-samples/serverless-snippets#34]
Please let us know what runtime you would like to see in the example snippet. We will collect the feedback and create an example in the requested runtime.

I miss PHP runtime... with Bref framework ;)

**Comment by boyney123** [comment]
@jhernandis we are adding PHP runtimes now, thanks for the comment. They are currently building built and will be live in the next couple of weeks.
